version: "3.7"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      TZ: Asia/Tokyo
    restart: always
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"

  php:
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./portfolio:/var/www
    depends_on:
      - mysql

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./portfolio:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  node:
    image: node:15
    container_name: node
    tty: true
    volumes:
      - ./portfolio:/app

volumes:
  data:
